from enum import auto, Enum
import numpy as np

class Space(Enum):
	EUCLIDEAN = auto()
	INNER_PRODUCT = auto()

class HnswlibIndexFloat:
	def __init__(self, space: Space, dim: int) -> None: ...
	def add_items(self, data: np.ndarray) -> None: ...
	def init_index(self, max_elements: int, M: int, ef_construction: int, seed: int) -> None: ...
	def knn_query(self, data: np.ndarray, k: int) -> tuple[np.ndarray, np.ndarray]: ...
	def set_ef(self, ef: int) -> None: ...
