import numpy as np

KnnResults = tuple[np.ndarray, np.ndarray]

class Space:
	...

class IHnsw:
	def __init__(self, space: Space, dim: int) -> None: ...
	def add_items(self, data: np.ndarray) -> None: ...
	def init_index(self, max_elements: int, M: int, ef_construction: int, seed: int) -> None: ...
	def knn_query(self, data: np.ndarray, k: int) -> KnnResults: ...
	def set_ef(self, ef: int) -> None: ...
